name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
      - uses: actions/cache@v1
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/dependency-locks/*.lockfile') }}
          restore-keys: |
            - ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        id: gradle-wrapper-cache
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/*') }}
          restore-keys: |
            - ${{ runner.os }}-gradlewrapper-
      - name: Build with Gradle
        run: ./gradlew --info --stacktrace build
        env:
          CI_NAME: github_actions
          CI_BUILD_NUMBER: ${{ github.sha }}
          CI_BUILD_URL: 'https://github.com/${{ github.repository }}'
          CI_BRANCH: ${{ github.ref }}
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
